name=ReticulumTransparentBridge
version=1.0.0
author=Custom
maintainer=Custom
sentence=A transparent bridge for Ebyte E90.
paragraph=Bypasses LilyGo path restrictions.
category=Communication
url=https://github.com/jgromes/RadioLib
architectures=esp32
includes=RadioLib.h
depends=RadioLib
